apiVersion: v1
version: 0.4.10
appVersion: 0.4.10
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: srikantt@users.noreply.github.com
  name: Srikanth Tanniru
sources:
- https://github.com/stefanprodan/podinfo
